services:
  api:
    build:
      context: ./backend
    container_name: atestados_api
    command: npm run start:dev
    env_file: ./.env
    ports:
      - "${API_PORT-3000}:3000"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongodb
      - redis

  web:
    build:
      context: ./frontend
    container_name: atestados_web
    command: npm run dev -- --host
    env_file: ./.env
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - api

  mongodb:
    image: mongo:7.0
    container_name: atestados_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7.2
    container_name: atestados_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  mongo_data:
