openapi: 3.0.0
paths:
  /api/health:
    get:
      operationId: HealthController_health
      parameters: []
      responses:
        "200":
          description: ""
      tags:
        - Health
  /api/icd/search:
    get:
      operationId: IcdController_search
      parameters: []
      responses:
        "200":
          description: ""
      tags:
        - ICD
  /api/collaborators:
    post:
      operationId: CollaboratorsController_create
      parameters: []
      responses:
        "201":
          description: ""
      tags: &a1
        - Collaborators
      security: &a2
        - bearer: []
    get:
      operationId: CollaboratorsController_search
      parameters: []
      responses:
        "200":
          description: ""
      tags: *a1
      security: *a2
  /api/collaborators/{cpf}:
    get:
      operationId: CollaboratorsController_getByCpf
      parameters: []
      responses:
        "200":
          description: ""
      tags: *a1
      security: *a2
    patch:
      operationId: CollaboratorsController_update
      parameters: []
      responses:
        "200":
          description: ""
      tags: *a1
      security: *a2
  /api/collaborators/{cpf}/status:
    patch:
      operationId: CollaboratorsController_updateStatus
      parameters: []
      responses:
        "200":
          description: ""
      tags: *a1
      security: *a2
  /api/medical-certificates:
    post:
      operationId: MedicalCertificatesController_create
      parameters: []
      responses:
        "201":
          description: ""
      tags: &a3
        - Medical Certificates
      security: &a4
        - bearer: []
    get:
      operationId: MedicalCertificatesController_list
      parameters: []
      responses:
        "200":
          description: ""
      tags: *a3
      security: *a4
  /api/medical-certificates/{id}/cancel:
    patch:
      operationId: MedicalCertificatesController_cancel
      parameters: []
      responses:
        "200":
          description: ""
      tags: *a3
      security: *a4
  /api/users:
    post:
      operationId: UsersController_create
      parameters: []
      responses:
        "201":
          description: ""
      tags: &a5
        - Users
      security: &a6
        - bearer: []
  /api/users/{email}:
    get:
      operationId: UsersController_get
      parameters: []
      responses:
        "200":
          description: ""
      tags: *a5
      security: *a6
  /api/users/{email}/status:
    patch:
      operationId: UsersController_updateStatus
      parameters: []
      responses:
        "200":
          description: ""
      tags: *a5
      security: *a6
  /api/users/{email}/roles:
    patch:
      operationId: UsersController_updateRoles
      parameters: []
      responses:
        "200":
          description: ""
      tags: *a5
      security: *a6
  /api/auth/login:
    post:
      operationId: AuthController_login
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginDto"
      responses:
        "201":
          description: ""
      tags: &a7
        - Auth
  /api/auth/logout:
    post:
      operationId: AuthController_logout
      parameters: []
      responses:
        "201":
          description: ""
      tags: *a7
      security:
        - bearer: []
info:
  title: Atestados API
  description: API de atestados médicos
  version: 1.0.0
  contact: {}
tags: []
servers: []
components:
  securitySchemes:
    bearer:
      scheme: bearer
      bearerFormat: JWT
      type: http
  schemas:
    LoginDto:
      type: object
      properties:
        email:
          type: string
          example: user@example.com
        password:
          type: string
          example: secret12345
          minLength: 8
      required:
        - email
        - password
